twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        custom_app_name: "%app_name%"
        author_name: '%author_name%'
        author_username: '%author_username%'
        author_webpage: '%author_webpage%'
