ServerStatus\Domain\Model\Customer\Customer:
  type: entity
  id:
    id:
      column: id
      type:   CustomerId
  table: customer
  repositoryClass: ServerStatus\Infrastructure\Domain\Model\Customer\DoctrineCustomerRepository
  embedded:
    email:
      class: ServerStatus\Domain\Model\Customer\CustomerEmail
      columnPrefix: "email_"
    alias:
      class: ServerStatus\Domain\Model\Customer\CustomerAlias
      columnPrefix: "alias_"
    status:
      class: ServerStatus\Domain\Model\Customer\CustomerStatus
      columnPrefix: "status_"
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [id]
  oneToMany:
      checks: # one customer has many checks
          #orderBy: { 'dates.start': 'DESC' }
          orphanRemoval: true
          mappedBy: customer
          cascade: ["all"]
          targetEntity: ServerStatus\Domain\Model\Check\Check
          joinColumn:
              name: check_id
              referencedColumnName: id
              nullable: false
              type: CheckId
