ServerStatus\Domain\Model\Check\Check:
    type: entity
    id:
        id:
          column: id
          type:   CheckId
    table: check_place
    repositoryClass: ServerStatus\Infrastructure\Domain\Model\Check\DoctrineCheckRepository
    embedded:
        name:
            class: ServerStatus\Domain\Model\Check\CheckName
            columnPrefix: "name_"
        url:
            class: ServerStatus\Domain\Model\Check\CheckUrl
            columnPrefix: "url_"
        status:
            class: ServerStatus\Domain\Model\Check\CheckStatus
            columnPrefix: "status_"

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [id]
    manyToOne:
        customer: # many checks have one customer
            targetEntity: ServerStatus\Domain\Model\Customer\Customer
            inversedBy: checks
            joinColumn:
                name: customer_id
                referencedColumnName: id
                nullable: false
                type: CustomerId
    oneToMany:
        measurements: # one check has many measurements
            #orderBy: { 'dates.start': 'DESC' }
            orphanRemoval: true
            mappedBy: check
            cascade: ["all"]
            targetEntity: ServerStatus\Domain\Model\Measurement\Measurement
            joinColumn:
                name: measurement_id
                referencedColumnName: id
                nullable: false
                type: MeasurementId
        alerts: # one check has many alerts
            #orderBy: { 'dates.start': 'DESC' }
            mappedBy: check
            orphanRemoval: true
            cascade: ["all"]
            targetEntity: ServerStatus\Domain\Model\Alert\Alert
            joinColumn:
                name: alert_id
                referencedColumnName: id
                nullable: true
                type: AlertId
